### ISSUE TITLE
Unable to add multiple creators

### ISSUE THREAD

**Issue by michaelbriordan** [urschrei/pyzotero#108] opened 2020-01-13 22:15 UTC
# General
Platform:  MacOS X
Python version:  3.7.5
Pyzotero version: latest release

# Problem description

Unable to create JSON arrays (creators) and objects (collections) with new items.

`template['creators'][0]['creatorType'] = "blah"`
 
works

`template['creators'][1]['creatorType'] = "blah" `

does not

Seems to also apply to objects, thus

`template['collections'][0] = "blah"`

returns

>  list assignment index out of range

- What were you trying to do?
    - What API call did it involve: Zotero.create_items
    - What error was raised?

Adding additional creatos raises no error but does not produce additional creators. Attempting to assign a collection returns:

> IndexError: list assignment index out of range

# If possible, paste the full traceback in a code block below, and fill in the summary

**Comment by urschrei** [comment] 2020-01-14 00:23
Could you add a little more context about _what_ you are trying to do?
What API call resulted in `template`? What are you hoping to pass it to?

**Comment by michaelbriordan** [comment] 2020-01-14 14:09
I am trying to use the `Zotero.create_items` method

exceptions are thrown when I try to assign a value to arrays or objects

1. Arrays

```
	template = zot.item_template(‘manuscript’) # I’m using ‘manuscript’ and ‘letter’ only with this script
         …  
	template['collections'][0] = "UBJW58IP"
        …
         resp = zot.create_items([template])
```

Raises exception:

> IndexError: list assignment index out of range

 If I remove this code, or pass over the exception, the item is created but no collection assigned.

2. Objects

```
	template = zot.item_template(‘letter’)
	…
	       template['creators'][1]['creatorType'] = 'recipient' 
               template['creators'][1]['firstName'] = “Some Other Person”
                template['creators'][1]['firstName'] = “Some Other Person”
        ...
               resp = zot.create_items([template])
```

raises an Index Exception, but the first object, ie. `template['creators'][0]['creatorType']` does not raise any exception. If I remove this code, or pass over the exception, the item is created, without the second creator.

**Comment by urschrei** [comment] 2020-02-23 17:45
I can't reproduce this:

    template = zot.item_template("manuscript")
    c = zot.collections()
    template["collections"].append(c[0]['key'])
    resp = zot.create_items([template])

Creates a new item as expected.

As for the second problem, unless I'm misunderstanding you, you need to append a `dict` containing creator data to the `creators` list first. You can't just specify a new key for a dict that doesn't exist yet: `creators` is a `list` with a single `dict` entry, so the `1` index doesn't work.

    template = zot.item_template("letter")
    creators_dict = template['creators'][0]
    template['creators'][0]['firstName'] = "foo"
    creators_dict['firstName'] = "bar"
    template['creators'].append(creators_dict)
    resp = zot.create_items([template])

In the absence of a reproducible example demonstrating an error, I'm going to close this issue. Feel free to reopen if something isn't working.

**Closed by urschrei** 2020-02-23 17:45 UTC
